config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'profile' => 'users#profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [ :index, :profile, :show ] do
    resources :teams, only: [ :new, :create, :index ]
  end
  resources :coworkings, only: [ :index, :show, :new, :create ] do
    resources :bookings, only: [ :index, :new, :create ]
  end
  resources :bookings, only: [ :destroy, :index ]
  resources :teams, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :coworking
end

def booked_date_range
  { from: :start_date, to: :end_date }
end

private

def end_date_after_start_date
  return if end_date.blank? || start_date.blank?
  if end_date < start_date
    errors.add(:end_date,"doit être après la date de début")
  end
end

app/models/coworking.rb
class Coworking < ApplicationRecord
  has_many :users, through: :bookings
  has_many :bookings
  has_many_attached :photos
  has_one_attached :avatar
  has_many :coworking_equipements
  has_many :equipements, through: :coworking_equipements

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/coworking_equipement.rb
class CoworkingEquipement < ApplicationRecord
  belongs_to :equipement
  belongs_to :coworking
end

app/models/equipement.rb
class Equipement < ApplicationRecord

end

app/models/team.rb
class Team < ApplicationRecord
  # belongs_to :manager, foreign_key: 'manager_id', class_name: 'User'
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :team, optional: true
  has_many :bookings, dependent: :destroy
  has_many :teams, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    ##### => a mettre a jour pour l'update du profil
    # devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings.where("date >= ?", Date.today)
                                     .order(date: :asc)
  end

  def create
    @coworking = Coworking.find(params[:coworking_id])
    @booking   = Booking.new(booking_params)
    @booking.coworking = @coworking
    @booking.user = current_user


    if @booking.save
      flash[:notice] = 'le coworking a bien été reservé'
      redirect_to bookings_path
    else
      @date = Date.today
      render 'coworkings/show'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date)
  end
end

app/controllers/coworkings_controller.rb
class CoworkingsController < ApplicationController
  before_action :find_coworking, only: [:show]
  def index
    if params[:booking_date]
      @date = Date.parse(params[:booking_date])
    else
      @date = Date.today
    end
    @coworkings = Coworking.all
    @markers = @coworkings.geocoded.map do |coworking|
      {
        lat: coworking.latitude,
        lng: coworking.longitude    
      }
    end
  end

  def show
    @coworking = Coworking.find(params[:id])
    @booking = Booking.new
    @coworkings = Coworking.all
    @markers = @coworkings.geocoded.map do |coworking|
      {
        lat: coworking.latitude,
        lng: coworking.longitude    
      }
    end

    # @date = Date.parse(params[:date])
    if params[:date]
      @date = Date.parse(params[:date])
    else
      @date = Date.today
    end
  end

  def new
    @coworking = Coworking.new
  end

  def create

    @coworking = Coworking.new(coworking_params)

    if @coworking.save # because we need an id
      # This should be out of this method and in a CoworkingEquipmentsController
      equipement_ids = params[:coworking]["equipement_ids"] # ["", "1", "2"]
      equipement_ids = equipement_ids.reject { |value| value.blank? }
      equipement_ids.each do |equipement_id|
        coworking_equipement =
          CoworkingEquipement.new(
            equipement_id: equipement_id,
            coworking: @coworking
          )
        coworking_equipement.save # what to do if errors ?

      end

      redirect_to coworking_path @coworking
    else
      render 'form'
    end
  end

  private

  def coworking_params
    params.require(:coworking).permit(:name, :address, :opening_time, :closing_time, :contact_name, :avatar, photos: [])
  end

  def find_coworking
    @coworking = Coworking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def profile
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :first_name, :last_name, :job_title, :phone_number, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([@coworking, @booking]) do |f| %>
<%= f.submit "réserver" %>
<% end %>
    
    

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/index.html.erb
<div class="container-fluid d-flex justify-content-center"
     style="margin-top: 64px;">
  <!-- UPCOMING BOOKINGS -->
  <div>
    <% @bookings.each do |booking| %>
      <div class="d-flex flex-row" style="margin-bottom: 64px;">
        <!-- div photo -->
        <div>
          <% if booking.coworking.photos.attached? %>
            <%= cl_image_tag(booking.coworking.photos.first.key, width:340, height: 228, crop: :fill)%>
          <% else %>
            <p>Photo à venir</p>
          <% end %>
        </div>
        <!-- div contenu -->
        <div class="w-50" style="margin-left: 48px;">
          <h2><%= booking.coworking.name %></h2>
          <p class="text-secondary"><%= booking.coworking.address %></p>

          <div class="d-flex" style="margin-top: 16px;">
            <span class="material-icons mr-2">&#xe614;</span>
            <p>Le <%= booking.date.strftime("%-d %b")%> . <%= booking.date.strftime("%Y") %></p>
          </div>

          <div type="button" class="btn btn-primary" style="margin-top: 16px ;">
            <%= link_to 'Annuler', booking_path(booking), method: :delete, data: { confirm: "Vous êtes sure ?" },:class => "btn"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div style="height: 200px;"></div>

app/views/bookings/new.html.erb
<div class="form-group">
    <label for="date">Choisissez une date, sélectionnez un bureau et réservez tout simplement ! </label>
    <input type="date" id="date" placeholder="DD/MM/YYYY" class="form-control">
  
    <%= f.submit %>
  </div>
  

app/views/coworkings/_form.html.erb
<div class="container">

  <div class="col-12 col-lg-6">

    <%= simple_form_for(@coworking) do |f| %>
      <%= f.error_notification %>

      <%= f.input :name%>
      <%= f.input :address%>
      <br>

      <h5>Equipements :</h5>

      <div class="row">
        <%= f.collection_check_boxes :equipement_ids, Equipement.all, :id, :name %>
      </div>
      <br>

      <h5>Horaires d'ouverture:</h5>

      <div class="d-flex justify-content-start ">
        <%= f.input :opening_time, as: :time, default: Time.parse('9:00') %>
        <%= f.input :closing_time, as: :time, default: Time.parse('19:00') %>
      </div>
      <br>

      <h5>Gestionnaire :</h5>

      <div class="row">
        <%= f.input :contact_name, label: 'Nom du gérant'%>

        <%= f.label "Photo du gérant" %>
        <%= f.file_field :avatar %>
      </div>
      <br>

      <h5>Photos du lieu :</h5>

      <div class="row">
        <%= f.label :photos, "Ajouter des photos" %>
        <%= f.file_field :photos, multiple: true, direct_upload: true %>
      </div>
      <br>

        <%= f.submit %>

    <% end %>
  </div>
</div>


<div style="height: 200px"></div>

<!-- t.string "name"
t.string "address"
t.datetime "created_at", precision: 6, null: false
t.datetime "updated_at", precision: 6, null: false
t.time "opening_time"
t.time "closing_time"
t.string "contact_name" -->

app/views/coworkings/create.html.erb
<%= render 'form' %>

app/views/coworkings/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="w-50" style="padding-left: 100px; padding-right: 48px;">

      <form action="/coworkings" method="get" class="w-50 d-flex">
        <input type="date" class="form-control" name="booking_date" value="<%= params[:booking_date] %>">
        <input type="submit" value="Valider la date" class="btn btn-primary ml-4">
      </form>

      <% @coworkings.each do |coworking| %>
        <div class="coworking-card">
          <% if coworking.photos.attached? %>
            <%= cl_image_tag(coworking.photos.first.key)%>
          <% else %>
            <p>Photo à venir</p>
          <% end %>

          <div>
            <h2><%= link_to coworking.name, coworking_path(coworking, date: @date) %></h2>
            <p><%= coworking.address %></p>

            <small class="text-secondary">
              <%= coworking.opening_time.hour %>h / <%= coworking.closing_time.hour %>h
              <% coworking.equipements.each do |equipement| %>
                <% equipement = equipement.name %>
                • <%= equipement %>
              <% end %>
            </small>
          </div>
        </div>

      <% end %>

    </div>
    
  <div id="map"
      class="w-50"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/coworkings/new.html.erb
<%= render 'form' %>

app/views/coworkings/show.html.erb
<div class="container-fluid">
  <div class="row">
  <!-- LEFT SIDE -->
    <div class="w-50" style="padding-left: 100px;">

      <!-- Revenir à la page précédente -->
      <div class="icon-text-left-black" style="margin-bottom: 32px;">
        <span class="material-icons">&#xe5cb;</span><%= link_to 'Revenir à la liste', coworkings_path %>
      </div>

      <!-- Carousel -->
      <div style="margin-bottom: 32px;">
        <% if @coworking.photos.size == 1 %>
            <img class="d-block w-100" src="<%= cl_image_path @coworking.photos.first.key %>" alt="photo" >

        <% elsif @coworking.photos.size > 1 %>
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <% @coworking.photos.size.times do |i| %>
                        <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>" class="<%= "active" if i.zero? %>"></li>
                    <% end %>
                </ol>

                <div class="carousel-inner">
                    <% @coworking.photos.each_with_index do |photo, index| %>
                        <div class="carousel-item <%= "active" if index.zero? %>">
                            <img class="d-block w-100" src="<%= cl_image_path photo.key %>" alt="<%= index.ordinalize %> image">
                        </div>
                    <% end %>
                </div>

                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>

                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        <% end %>
      </div>

      <!-- Avatar du gérant -->
      <div class="d-flex align-items-center">
        <% if @coworking.avatar.attached? %>
          <%= cl_image_tag @coworking.avatar.key, class: 'avatar-medium' %>
        <% else %>
          <p>Je n'ai pas de photo - mettre une image par défaut</p>
        <% end %>
        <p class="mt-3 ml-3"><%= @coworking.contact_name %>, gestionnaire de l’espace <%= @coworking.name %></p>

      </div>
    </div>

    <!-- RIGHT SIDE -->
    <div class="w-50" style="margin-top:64px ;padding-left: 48px;">

      <h1><%= @coworking.name %></h1>
      <p><%= @coworking.address %></p>
      <h2 class="d-inline-flex align-items-center mt-1" style="color: #4086CE;"><span class="material-icons pr-2" style="font-size: 40px;">&#xe8b5;</span><%= " Ouvert de #{@coworking.opening_time.hour}h à " %><%= @coworking.closing_time.hour %>h </h2>

      <div type="button" style="margin-top: 32px">
          <%= simple_form_for([@coworking, @booking]) do |f| %>
          <%= f.input :date, as: :hidden, input_html: { value: @date } %>
          <%= f.submit "Réserver le #{@date.strftime("%-d %b")}. #{@date.strftime("%Y")}", class: "btn btn-primary btn-book" %>
          <% end %>

      </div>

      <div style="margin-top: 48px">
        <ul class = "list-unstyled">

          <% @coworking.equipements.each do |equipement|%>
            <li class="d-inline border border-secondary text-secondary rounded-pill mr-4 p-2 text-nowrap">

              <% equipement_name = equipement.name %>

              <% if equipement_name == "Accès PMR" %><span class="material-icons align-top mb-4">&#xe914;</span><% end %>
              <% if equipement_name == "Doc. unique de secu" %><span class="material-icons align-top mb-4">&#xe85d;</span><% end %>
              <% if equipement_name == "Espace repas" %><span class="material-icons align-top mb-4">&#xe561;</span><% end %>
              <% if equipement_name == "Fauteuils ergonomiques" %><span class="material-icons align-top mb-4">&#xe903;</span><% end %>
              <% if equipement_name == "Firewall" %><span class="material-icons align-top mb-4">&#xe32a;</span><% end %>
              <% if equipement_name == "Imprimante" %><span class="material-icons align-top mb-4">&#xe8ad;</span><% end %>
              <% if equipement_name == "Internet Haut Débit" %><span class="material-icons align-top mb-4">&#xe63e;</span><% end %>
              <% if equipement_name == "Parking Gratuit" %><span class="material-icons align-top mb-4">&#xe531;</span><% end %>
              <%= "#{equipement_name}" %>

            </li>

          <% end %>
        </ul>
      </div>

  <div id="map"
      class="w-50 vh-100"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
    </div>
  </div>
</div>

<div style="height: 200px;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Extramuros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" >
  <div class="container">
    <h1>Trouvez un coworking<br>près de chez vous !</h1>
    <p>Sélectionnez un bureau et réservez, tout simplement !</p>
    <div type="button" class="btn btn-primary" style="margin-top: 32px ;">
      <%= link_to 'Réservez votre place', coworkings_path, :class => "btn"%>
    </div>
  </div>
</div>

app/views/shared/_equipements.html.erb
<ul>
  <li class="d-inline border border-secondary text-secondary rounded-pill mr-4 p-2 text-nowrap">
    <%= "#{@coworking.opening_time.hour}" %>h / <%= @coworking.closing_time.hour %>h <span class="material-icons align-top mb-4">&#xe8b5;</span>
  </li>

  <% @coworking.equipements.each do |equipement|%>
    <li class="d-inline border border-secondary text-secondary rounded-pill mr-4 p-2 text-nowrap">

      <% equipement_name = equipement.name %>

      <% if equipement_name == "Accès PMR" %><span class="material-icons align-top mb-4">&#xe914;</span><% end %>
      <% if equipement_name == "Doc. unique de secu" %><span class="material-icons align-top mb-4">&#xe85d;</span><% end %>
      <% if equipement_name == "Espace repas" %><span class="material-icons align-top mb-4">&#xe561;</span><% end %>
      <% if equipement_name == "Fauteuils ergonomiques" %><span class="material-icons align-top mb-4">&#xe903;</span><% end %>
      <% if equipement_name == "Firewall" %><span class="material-icons align-top mb-4">&#xe32a;</span><% end %>
      <% if equipement_name == "Imprimante" %><span class="material-icons align-top mb-4">&#xe8ad;</span><% end %>
      <% if equipement_name == "Internet Haut Débit" %><span class="material-icons align-top mb-4">&#xe63e;</span><% end %>
      <% if equipement_name == "Parking Gratuit" %><span class="material-icons align-top mb-4">&#xe531;</span><% end %>
      <%= "#{equipement_name}" %>

    </li>

  <% end %>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path, class: "navbar-brand" do %>
    extramuros
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item active">
          <%= link_to "Mes réservations", bookings_path, class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Mon compte", profile_path, class: "nav-link" %>
        </li>

<!--         <li class="nav-item active">
        </li> -->

        <li class="nav-item active">
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>

        <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_user_profile.html.erb
<div class="container-fluid">
  <div class="row" style="margin-top: 64px ;">
    <div class="col 12 col-sm-4 column-profile" style="margin-top: 16px;">
      <div class="card-user-profile">
        <%= image_tag @user.avatar, class: "avatar-large" %>
        <div class="card-user-profile-content">
          <h2><%= @user.first_name %> <%= @user.last_name %></h2>
          <%= @user.job_title %>
          <div class="icon-text-left-mixt">
            <span class="material-icons">&#xe0be;</span><%= @user.email %>
          </div>
          <div class="icon-text-left-mixt">
            <span class="material-icons">&#xe0cd;</span><%= @user.phone_number %>
          </div>

          <% if @current_user %>
            <div style="margin-top: 32px ; padding-top: 32px; border-top:1px solid #E5E5E5;"></div>
              <!-- n'apparait que si current_user -->
              <div class="icon-text-right">
                éditer mon profil<span class="material-icons">&#xe3c9;</span>
              </div>
          <% end %>
        </div>
      </div>

    </div>
    <div class="col 12 col-sm-8 column-stats">
      <h1>Toutes mes stats</h1>

      <p class="text-secondary">
        <% if current_user %>
          Retrouvez ici tous vos chiffres clés !
        <% else %>
          Retrouvez ici tous les chiffres clés pour <span><%= @user.first_name %> <%= @user.last_name %></span>!
        <% end %>
      </p>

      <div class="icon-text-left-big">
        <span class="material-icons">&#xe614;</span>
        Vous avez la possibilité de télétravailler en coworking&nbsp;
        <h3 style="color: #4086CE;"><%= @user.allowed_days_per_weeks %> jours </h3 style="background-color: blue;">&nbsp;par semaine.
      </div>

      <div class="icon-text-left-big">
        <span class="material-icons">&#xe889;</span>
        Vous avez passé&nbsp;
        <h3 style="color: #4086CE;"><%= @user.bookings.where("date < ?", Date.today).count %> jours </h3 style="background-color: blue;">&nbsp;en coworking depuis le 1er janvier 2021.
      </div>
      <div class="icon-text-left-big">
        <span class="material-icons">&#xea1c;</span>
        <h3 style="color: #4086CE;"> </h3 style="background-color: blue;">&nbsp;<em>Complétez votre profil pour connaître la réduction de votre emprunte écologique . </em>
      </div>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/profile.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lx-4 column-profile">
      <div class="card-user-profile">
        <%= image_tag @user.avatar, class: "avatar-large" %>
        <div class="card-user-profile-content">
          <h2><%= @user.first_name %> <%= @user.last_name %></h2>
          <%= @user.job_title %>
          <div class="icon-text-left">
            <span class="material-icons">&#xe0be;</span><%= @user.email %>
          </div>
          <div class="icon-text-left">
            <span class="material-icons">&#xe0cd;</span><%= @user.phone_number %>
          </div>
          <div style="margin-top: 32px ; padding-top: 32px; border-top:1px solid #E5E5E5;"></div>
          <!-- n'apparait que si current_user -->
          <% if current_user %>
            <div class="icon-text-right">
              éditer mon profil<span class="material-icons">&#xe3c9;</span>
            </div>
          <% end %>
        </div>
      </div>

    </div>
    <div class="col-lx-8 column-stats">
      <h1>Toutes mes stats</h1>

      <% if current_user %>
        (à supprimer) current user: <span><%= @user.first_name %> <%= @user.last_name %> <%= @user.id %></span><br>
        Retrouvez ici tous vos chiffres clés !
      <% else %>
        Retrouvez ici tous les chiffres clés pour <span><%= @user.first_name %> <%= @user.last_name %></span>!
      <% end %>

      <div class="icon-text-left-big">
        <span class="material-icons">&#xe614;</span>
        Vous avez la possibilité de télétravailler en coworking&nbsp;
        <h3 style="color: #4086CE;"><%= @user.allowed_days_per_weeks %> jours </h3 style="background-color: blue;">&nbsp;par semaine.
      </div>
      <div class="icon-text-left-big">
        <span class="material-icons">&#xe889;</span>
        Vous avez passé&nbsp;
        <h3 style="color: #4086CE;"><%= @user.allowed_days_per_weeks %> jours </h3 style="background-color: blue;">&nbsp;en coworking depuis le 1er janvier 2022.
      </div>
      <div class="icon-text-left-big">
        <span class="material-icons">&#xea1c;</span>
        Vous avez réduit de&nbsp;
        <h3 style="color: #4086CE;"><%= @user.allowed_days_per_weeks %>% </h3 style="background-color: blue;">&nbsp;vos émissions de CO2 depuis le 1er janvier 2022.
      </div>
      <div class="icon-text-left-big">
        <span class="material-icons">&#xf20c;</span>
        Vous passez&nbsp;
        <h3 style="color: #4086CE;"><%= @user.allowed_days_per_weeks %>% </h3 style="background-color: blue;">&nbsp;de votre temps de travail dans les locaux de l’entreprise depuis le 1er janvier 2022.
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/user_profile' %>